### ISSUE TITLE
Issue when using lprun: NullReferenceException: Object reference not set to an instance of an object

### ISSUE THREAD

**Issue by maboivin** [meancrazy/LINQPadOData4#15]
Hi,
The OData 4 driver doesn't seem to play well with lprun.exe. When querying an OData 4 source and using lprun.exe to run the script, there's always an error. I'm using LINQPad v5.10.00 with the driver v1.0.3.4.

I used the following simple script:
`
var x = this.MyEntities.ToArray();
`

and it produced the following error:

``
D:\apps\LINQPad5>lprun.exe "C:\Users\maboivin\Documents\LINQPad Queries\test.linq"
NullReferenceException: Object reference not set to an instance of an object.
   at OData4.OData4DynamicDriver.<>c__DisplayClass19_0.<InitializeContext>b__1(Object s, SendingRequest2EventArgs e)
   at Microsoft.OData.Client.DataServiceContext.FireSendingRequest2(SendingRequest2EventArgs eventArgs)
   at Microsoft.OData.Client.ODataRequestMessageWrapper.FireSendingRequest2(Descriptor descriptor)
   at Microsoft.OData.Client.DataServiceRequest.CreateExecuteResult(Object source, DataServiceContext context, AsyncCallback callback, Object state, String method)
   at Microsoft.OData.Client.DataServiceRequest.Execute[TElement](DataServiceContext context, QueryComponents queryComponents)
   at Microsoft.OData.Client.DataServiceQuery`1.Execute()
   at Microsoft.OData.Client.DataServiceQuery`1.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at UserQuery in C:\Users\maboivin\Documents\LINQPad Queries\test.linq:line 1
   at LINQPad.ExecutionModel.ClrQueryRunner.Run()
   at LINQPad.ExecutionModel.Server.RunQuery(QueryRunner runner)
``

**Comment by maboivin** [comment]
After reviewing the code, the issue seems to be that the SqlTranslationWriter is null:  https://github.com/meancrazy/LINQPadOData4/blob/c6eb3123e6fa7ab3ea4afd1238d7d9f692b9ed11/OData4DynamicDriver.cs#L177

The following quickly fixes (already tested using linqpad and lprun) the issue using the null-conditional operator:

            dsContext.SendingRequest2 += (s, e) =>
            {
                executionManager.SqlTranslationWriter?.WriteLine($"URL:\t\t{e.RequestMessage.Url}");

                if (properties.LogMethod)
                    executionManager.SqlTranslationWriter?.WriteLine($"Method:\t{e.RequestMessage.Method}");

                if (properties.LogHeaders)
                {
                    executionManager.SqlTranslationWriter?.WriteLine("Headers:");
                    var headers = string.Join("\r\n", e.RequestMessage.Headers.Select(o => $"\t{o.Key}:{o.Value}"));
                    executionManager.SqlTranslationWriter?.WriteLine(headers);
                }
            };

**Comment by meancrazy** [comment]
fix in [new](/meancrazy/LINQPadOData4/releases/tag/1.0.3.7) build
